version: '3.3'
services:
  backend:
    build:
      context: ../backend
    volumes:
      # Контейнер web будет работать с данными, хранящиеся в томе static_value,
      # через свою директорию /app/static/
      - static_value:/app/static/
      # Данные, хранящиеся в томе media_value, будут доступны в контейнере web
      # через директорию /app/media/
      - media_value:/app/media/
    # «зависит от»,
    depends_on:
      - db
    env_file:
      - ./.env
#  backend:
##    build: ../backend
#    command: python manage.py runserver 0.0.0.0:8000
#    volumes:
#      - ../backend:/app
#    ports:
#      - "8000:8000"
  db:
    image: postgres:14-alpine
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data/
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/
  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
volumes:
  db_data:
  static_value:
  media_value:
  frontend_value:

