# Generated by Django 4.1.7 on 2023-04-14 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_subscribe_options_alter_subscribe_author_and_more'),
    ]

    operations = [
    ]
